config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boba_teas do 
    resources :reviews
  end
  root 'boba_teas#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boba_shop.rb
class BobaShop < ApplicationRecord
    has_many :boba_teas
end

app/models/boba_tea.rb
class BobaTea < ApplicationRecord
#only user can delete the content they created, it has user_id
belongs_to :user, optional: true
belongs_to :boba_shop, optional: true
has_many :reviews
has_many :users, through: :reviews
has_attached_file :boba_tea_img, :styles => { :boba_tea_index => "250x350>", :boba_tea_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :boba_tea_img, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :boba_tea
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :boba_teas, through: :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boba_teas_controller.rb
class BobaTeasController < ApplicationController
    before_action :find_boba_tea, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def index
        if params[:boba_shop].blank?
			@boba_teas = BobaTea.all.order("created_at DESC")
		else
			@boba_shop_id = BobaShop.find_by(name: params[:boba_shop]).id
			@boba_teas = BobaTea.where(:boba_shop_id => @boba_shop_id).order("created_at DESC")
		end
      end
  
      def new
          @boba_tea = current_user.boba_teas.build
          @boba_shops =BobaShop.all.map{|s| [s.name, s.id]}
      end
  
      def create
          @boba_tea = current_user.boba_teas.build(boba_tea_params)
          @boba_tea.boba_shop_id = params[:boba_shop_id]
          if @boba_tea.save
              redirect_to  boba_tea_path(@boba_tea), notice:'Boba Tea was successfully created'
          else  
              render 'new'
          end
      end
  
      def show
        #   @reviews = Review.where(boba_tea_id: @boba_tea)
          if @boba_tea.reviews.blank?
              @average_review = 0
          else
              @average_review = @boba_tea.reviews.average(:rating).round(2)
          end
      end
      
      def edit
        @boba_shops =BobaShop.all.map{|s| [s.name, s.id]}
      end

      def update
        @boba_tea.boba_shop_id = params[:boba_shop_id]
        if @boba_tea.update(boba_tea_params)
            redirect_to boba_tea_path(@boba_tea)
        else  
            render 'edit'
        end
      end

      def destroy
       @boba_tea.destroy
       redirect_to root_path
      end

      private 

       def find_boba_tea
         @boba_tea = BobaTea.find(params[:id])
       end

       def boba_tea_params
          params.require(:boba_tea).permit(:name, :description, :boba_shop_id, :boba_tea_img)
       end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_boba_tea
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    
    def new
        @review = Review.new
    end

    def create
        @review = Review.create(review_params)
        @review.user_id = current_user.id
        @review.boba_tea_id = @boba_tea.id 
        if @review.save
            redirect_to boba_tea_path(@boba_tea), notice:"Review was successfully created"
        else  
            render "new"
        end
    end

    def edit
    end

    def update
        if @review.update(review_params)
            redirect_to boba_tea_path(@boba_tea)
        else  
            render 'edit'
        end
    end

    def destroy
        @review.destroy
        redirect_to boba_tea_path(@boba_tea)
    end

    private
    def find_review
        @review = Review.find(params[:id])
    end

    def find_boba_tea
        @boba_tea = BobaTea.find(params[:boba_tea_id])
    end
    def review_params
        params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boba_teas_helper.rb
module BobaTeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/boba_teas/_form.html.erb
<%= simple_form_for @boba_tea, :html => { :multipart => true } do |f| %>
	<%= select_tag(:boba_shop_id, options_for_select(@boba_shops), :prompt => "Select Boba Shop") %>
    <%= f.file_field :boba_tea_img %>
	<%= f.input :name, label: "Boba Tea Name" %>
	<%= f.input :description, label:"Description"%>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/boba_teas/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-boba-tea-form">   

     <h1>Edit Boba Tea</h1>
    <%= simple_form_for @boba_tea, :html => { :multipart => true } do |f| %>
	  <%= f.select :boba_shop_id, @boba_shops %>
      <%= f.file_field :boba_tea_img %>
	  <%= f.input :name, label: "Boba Tea Name" %>
	  <%= f.input :description, label:"Description"%>
	  <%= f.button :submit, :class => "btn-custom2" %>
    <% end %>
    
  </div>
</div>

app/views/boba_teas/index.html.erb
<h1 class="current-boba-shop"><%= params[:boba_shop] %></h1>

<% if @boba_teas.count == 0 %>

  <h1>There is no any reviewed boba tea in this shop</h1>

<%else%>

  <div class="row">

		<% @boba_teas.each do |boba_tea| %>

			<div class="col-md-4">
                <p class="boba-tea-desc"><%= boba_tea.name %></p>
				<a href="/boba_teas/<%= boba_tea.id %>">
					<%= image_tag boba_tea.boba_tea_img.url(:boba_tea_index), class: "boba-tea" %>
				</a>
			</div>	

		<% end %>

	</div>
          
<% end %>
<%= link_to "Add Boba Tea", new_boba_tea_path %>

app/views/boba_teas/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-boba-tea-form">

    <h1>Share Your Favorite Boba Tea</h1>
      <%= render 'form' %>
      
  </div>
</div>

app/views/boba_teas/show.html.erb
<div class="row">

	<div class="col-md-4">

      <%= image_tag @boba_tea.boba_tea_img.url(:boba_tea_show), class: "boba-tea-show"%>

	</div>

	<div class="col-md-4">

		<div class="boba-tea-info">
             <h2 class="boba-tea-title"><%= @boba_tea.name %></h2>
             <p class="boba-shop-name"><span>Boba shop:</span> <%= @boba_tea.boba_shop.name %></p>
             <h3 class="avg-rating">Average Rating</h3>
			 <div class="average-review-rating" data-score=<%= @average_review %>></div>
             <span class="number-of-reviews">Total <%= @boba_tea.reviews.count %> reviews</span>
             <p class="boba-tea-desc"><%= @boba_tea.description %></p>
             
        </div>
	</div>

    <div class="row">

	<div class="col-md-7">

       <div class="reviews">

        <h1>Reviews</h1>
        <%= render @boba_tea.reviews %>

		  <div>
			  <%= link_to "Add Review", new_boba_tea_review_path(@boba_tea), class: "btn-custom" %>
		  </div>

		</div>	

	</div>

</div>
<div class="links btn-group">
    <%= link_to "Back", root_path, class:"btn btn-custom" %>

    <% if user_signed_in? %>
      <% if @boba_tea.user_id == current_user.id %>
        <%= link_to "Edit", edit_boba_tea_path(@boba_tea), class:"btn btn-custom" %>
        <%= link_to "Delete", boba_tea_path(@boba_tea), method: :delete, data: {confirm:"Are you sure?"}, class:"btn btn-custom" %>
      <%end%>
    <%end%>
</div>
<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playboba</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     	<nav class="navbar navbar-default">

		    <div class="container">

			      <div class="navbar-header">
				      <%= link_to "Play Boba", root_path, class: "navbar-brand" %>
			      </div>

			      <ul class="nav navbar-nav">
				      <li><%= link_to "Sign Up", new_user_registration_path %></li>
				      <% if user_signed_in? %>
					    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				      <% else %>	
					  <li><%= link_to "Log In", new_user_session_path %></li>
				    <% end %>
			      </ul>

			      <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Boba Shops <span class="caret"></span></a>
					        <ul class="dropdown-menu" role="menu">
						        <% BobaShop.all.each do |boba_shop| %>
							        <li class="<%= 'active' if params[:boba_shop] == boba_shop.name %>">
								        <%= link_to boba_shop.name, boba_teas_path(boba_shop: boba_shop.name), class: "link" %>
							        </li>
						        <% end %>
                  </ul>
                </li>
            
				      <% if user_signed_in? %>
					    <li><%= link_to "Add Boba Teas", new_boba_tea_path %></li>
				      <% end %>
				
			      </ul>

		    </div>

	    </nav>

    
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

	<% if !user_signed_in? %>
        <div class="jumbotron">
          <h1 class="display-4 boba">Rate Your Favorite Boba Tea</h1>
          <p class="lead boba"><span class="boba-text">If you love Boba tea as much as us ᕙ(^▿^-ᕙ)</span>(ɔ◔‿◔)ɔ ♥Share your opinion with Boba Lovers!</p>
          <hr class="my-4">
        </div>
    <% end %>

      <div class="container"> 
    <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@boba_tea, @boba_tea.reviews.build]) do |f| %>

    <div id="rating-form">
		<label>Rating</label>
	</div>

	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating%>"></div>
  <p class="review-comment"><%= review.comment %></p>
    
  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
        <%= link_to "Edit", edit_boba_tea_review_path(review.boba_tea, review), class: "btn btn-custom" %>
        <%= link_to "Delete", boba_tea_review_path(review.boba_tea, review), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-custom" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-review-form">

    <h1>Edit Review</h1>
      <%= simple_form_for([@boba_tea, @review]) do |f| %>
        <div id="rating-form">
		  <label>Rating</label>
        </div>
       <%= f.input :comment %>
       <%= f.button :submit, :class => "btn-custom2" %>
      <% end %>
  </div>
</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-review-form">

    <h1>New Review</h1>
    <%= render "form" %>
    
  </div>
</div>